/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hybmesh_Worker */

#ifndef _Included_Hybmesh_Worker
#define _Included_Hybmesh_Worker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hybmesh_Worker
 * Method:    require_connection
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Hybmesh_00024Worker_require_1connection
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Hybmesh_Worker
 * Method:    get_signal
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_Hybmesh_00024Worker_get_1signal
  (JNIEnv *, jobject, jint);

/*
 * Class:     Hybmesh_Worker
 * Method:    send_signal
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_Hybmesh_00024Worker_send_1signal
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     Hybmesh_Worker
 * Method:    get_data
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Hybmesh_00024Worker_get_1data
  (JNIEnv *, jobject, jint);

/*
 * Class:     Hybmesh_Worker
 * Method:    send_data
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_Hybmesh_00024Worker_send_1data
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     Hybmesh_Worker
 * Method:    break_connection
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Hybmesh_00024Worker_break_1connection
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif

