/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HybMesh */

#ifndef _Included_HybMesh
#define _Included_HybMesh
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HybMesh
 * Method:    require_connection
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_HybMesh_require_1connection
  (JNIEnv *, jobject);

/*
 * Class:     HybMesh
 * Method:    get_signal
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_HybMesh_get_1signal
  (JNIEnv *, jobject, jint);

/*
 * Class:     HybMesh
 * Method:    send_signal
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_HybMesh_send_1signal
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     HybMesh
 * Method:    get_data
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_HybMesh_get_1data
  (JNIEnv *, jobject, jint);

/*
 * Class:     HybMesh
 * Method:    send_data
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_HybMesh_send_1data
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     HybMesh
 * Method:    break_connection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HybMesh_break_1connection
  (JNIEnv *, jobject, jint);


#ifdef __cplusplus
}
#endif
#endif
