# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddUnfRingDlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_add_unf_ring(object):
    def setupUi(self, add_unf_ring):
        add_unf_ring.setObjectName(_fromUtf8("add_unf_ring"))
        add_unf_ring.resize(400, 220)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(add_unf_ring.sizePolicy().hasHeightForWidth())
        add_unf_ring.setSizePolicy(sizePolicy)
        add_unf_ring.setMinimumSize(QtCore.QSize(400, 220))
        add_unf_ring.setMaximumSize(QtCore.QSize(400, 220))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/mainwin.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        add_unf_ring.setWindowIcon(icon)
        self.gridLayout_4 = QtGui.QGridLayout(add_unf_ring)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.frame_4 = QtGui.QFrame(add_unf_ring)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.frame_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.ed_name = QtGui.QLineEdit(self.frame_4)
        self.ed_name.setObjectName(_fromUtf8("ed_name"))
        self.horizontalLayout.addWidget(self.ed_name)
        self.gridLayout_4.addWidget(self.frame_4, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(193, 33, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 2)
        self.frame = QtGui.QFrame(add_unf_ring)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.ed_x = QtGui.QLineEdit(self.frame)
        self.ed_x.setObjectName(_fromUtf8("ed_x"))
        self.gridLayout.addWidget(self.ed_x, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.ed_y = QtGui.QLineEdit(self.frame)
        self.ed_y.setObjectName(_fromUtf8("ed_y"))
        self.gridLayout.addWidget(self.ed_y, 1, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(add_unf_ring)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.ed_irad = QtGui.QLineEdit(self.frame_2)
        self.ed_irad.setObjectName(_fromUtf8("ed_irad"))
        self.gridLayout_2.addWidget(self.ed_irad, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.ed_orad = QtGui.QLineEdit(self.frame_2)
        self.ed_orad.setObjectName(_fromUtf8("ed_orad"))
        self.gridLayout_2.addWidget(self.ed_orad, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 1, 1, 1, 2)
        self.frame_3 = QtGui.QFrame(add_unf_ring)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_3 = QtGui.QLabel(self.frame_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.ed_na = QtGui.QLineEdit(self.frame_3)
        self.ed_na.setObjectName(_fromUtf8("ed_na"))
        self.gridLayout_3.addWidget(self.ed_na, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.ed_nr = QtGui.QLineEdit(self.frame_3)
        self.ed_nr.setObjectName(_fromUtf8("ed_nr"))
        self.gridLayout_3.addWidget(self.ed_nr, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 2, 0, 2, 1)
        self.frame_5 = QtGui.QFrame(add_unf_ring)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.frame_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.ed_coef = QtGui.QLineEdit(self.frame_5)
        self.ed_coef.setObjectName(_fromUtf8("ed_coef"))
        self.horizontalLayout_2.addWidget(self.ed_coef)
        self.gridLayout_4.addWidget(self.frame_5, 2, 1, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(189, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 4, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(add_unf_ring)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 4, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 34, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 3, 1, 1, 1)

        self.retranslateUi(add_unf_ring)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), add_unf_ring.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), add_unf_ring.reject)
        QtCore.QMetaObject.connectSlotsByName(add_unf_ring)

    def retranslateUi(self, add_unf_ring):
        add_unf_ring.setWindowTitle(_translate("add_unf_ring", "Add ring uniform grid block", None))
        self.label.setText(_translate("add_unf_ring", "Grid name", None))
        self.ed_name.setText(_translate("add_unf_ring", "RingGrid1", None))
        self.ed_x.setText(_translate("add_unf_ring", "0.0", None))
        self.label_7.setText(_translate("add_unf_ring", "Y", None))
        self.label_6.setText(_translate("add_unf_ring", "X", None))
        self.ed_y.setText(_translate("add_unf_ring", "0.0", None))
        self.label_2.setText(_translate("add_unf_ring", "Inner Radius", None))
        self.ed_irad.setText(_translate("add_unf_ring", "1.0", None))
        self.label_8.setText(_translate("add_unf_ring", "Outer Radius", None))
        self.ed_orad.setText(_translate("add_unf_ring", "2.0", None))
        self.label_3.setText(_translate("add_unf_ring", "Arch partition", None))
        self.ed_na.setText(_translate("add_unf_ring", "10", None))
        self.label_4.setText(_translate("add_unf_ring", "Radius partition", None))
        self.ed_nr.setText(_translate("add_unf_ring", "10", None))
        self.label_5.setText(_translate("add_unf_ring", "Refinement coef", None))
        self.ed_coef.setText(_translate("add_unf_ring", "1.2", None))

import ComGridRes_rc
