# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ComGridMain.ui'
#
# Created by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/mainwin.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.f_vtk = QtGui.QFrame(self.centralwidget)
        self.f_vtk.setFrameShape(QtGui.QFrame.StyledPanel)
        self.f_vtk.setFrameShadow(QtGui.QFrame.Sunken)
        self.f_vtk.setObjectName(_fromUtf8("f_vtk"))
        self.verticalLayout_2.addWidget(self.f_vtk)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        self.menu_Geometry = QtGui.QMenu(self.menubar)
        self.menu_Geometry.setObjectName(_fromUtf8("menu_Geometry"))
        self.menuAdd_grid = QtGui.QMenu(self.menu_Geometry)
        self.menuAdd_grid.setObjectName(_fromUtf8("menuAdd_grid"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuTransform = QtGui.QMenu(self.menubar)
        self.menuTransform.setObjectName(_fromUtf8("menuTransform"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.DWGridManager = QtGui.QDockWidget(MainWindow)
        self.DWGridManager.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.DWGridManager.setObjectName(_fromUtf8("DWGridManager"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tw_gridblocks = QtGui.QTreeWidget(self.dockWidgetContents)
        self.tw_gridblocks.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tw_gridblocks.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.tw_gridblocks.setColumnCount(5)
        self.tw_gridblocks.setObjectName(_fromUtf8("tw_gridblocks"))
        self.tw_gridblocks.headerItem().setText(0, _fromUtf8("1"))
        self.tw_gridblocks.headerItem().setText(1, _fromUtf8("2"))
        self.tw_gridblocks.headerItem().setText(2, _fromUtf8("3"))
        self.tw_gridblocks.headerItem().setText(3, _fromUtf8("4"))
        self.tw_gridblocks.headerItem().setText(4, _fromUtf8("5"))
        self.tw_gridblocks.header().setVisible(False)
        self.verticalLayout.addWidget(self.tw_gridblocks)
        self.DWGridManager.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.DWGridManager)
        self.act_open = QtGui.QAction(MainWindow)
        self.act_open.setObjectName(_fromUtf8("act_open"))
        self.act_save = QtGui.QAction(MainWindow)
        self.act_save.setObjectName(_fromUtf8("act_save"))
        self.act_exit = QtGui.QAction(MainWindow)
        self.act_exit.setObjectName(_fromUtf8("act_exit"))
        self.act_undo = QtGui.QAction(MainWindow)
        self.act_undo.setObjectName(_fromUtf8("act_undo"))
        self.act_redo = QtGui.QAction(MainWindow)
        self.act_redo.setObjectName(_fromUtf8("act_redo"))
        self.act_comhist = QtGui.QAction(MainWindow)
        self.act_comhist.setCheckable(True)
        self.act_comhist.setChecked(False)
        self.act_comhist.setObjectName(_fromUtf8("act_comhist"))
        self.act_unf_rect = QtGui.QAction(MainWindow)
        self.act_unf_rect.setObjectName(_fromUtf8("act_unf_rect"))
        self.act_grid_manager = QtGui.QAction(MainWindow)
        self.act_grid_manager.setCheckable(True)
        self.act_grid_manager.setChecked(True)
        self.act_grid_manager.setObjectName(_fromUtf8("act_grid_manager"))
        self.act_unite_grids = QtGui.QAction(MainWindow)
        self.act_unite_grids.setObjectName(_fromUtf8("act_unite_grids"))
        self.act_unf_circ = QtGui.QAction(MainWindow)
        self.act_unf_circ.setObjectName(_fromUtf8("act_unf_circ"))
        self.act_movrot = QtGui.QAction(MainWindow)
        self.act_movrot.setObjectName(_fromUtf8("act_movrot"))
        self.menu_File.addAction(self.act_open)
        self.menu_File.addAction(self.act_save)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.act_exit)
        self.menu_Edit.addAction(self.act_undo)
        self.menu_Edit.addAction(self.act_redo)
        self.menu_View.addAction(self.act_comhist)
        self.menu_View.addAction(self.act_grid_manager)
        self.menuAdd_grid.addAction(self.act_unf_rect)
        self.menuAdd_grid.addAction(self.act_unf_circ)
        self.menu_Geometry.addAction(self.menuAdd_grid.menuAction())
        self.menuTools.addAction(self.act_unite_grids)
        self.menuTransform.addAction(self.act_movrot)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Geometry.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuTransform.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.act_exit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.act_grid_manager, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.DWGridManager.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit", None))
        self.menu_View.setTitle(_translate("MainWindow", "&View", None))
        self.menu_Geometry.setTitle(_translate("MainWindow", "&Geometry", None))
        self.menuAdd_grid.setTitle(_translate("MainWindow", "Add &grid", None))
        self.menuTools.setTitle(_translate("MainWindow", "&Tools", None))
        self.menuTransform.setTitle(_translate("MainWindow", "Trans&form", None))
        self.DWGridManager.setWindowTitle(_translate("MainWindow", "Grid Manager", None))
        self.act_open.setText(_translate("MainWindow", "&Open ...", None))
        self.act_save.setText(_translate("MainWindow", "&Save ...", None))
        self.act_exit.setText(_translate("MainWindow", "E&xit", None))
        self.act_undo.setText(_translate("MainWindow", "&Undo", None))
        self.act_undo.setShortcut(_translate("MainWindow", "Ctrl+Z", None))
        self.act_redo.setText(_translate("MainWindow", "&Redo", None))
        self.act_redo.setShortcut(_translate("MainWindow", "Ctrl+Y", None))
        self.act_comhist.setText(_translate("MainWindow", "Commands &history", None))
        self.act_unf_rect.setText(_translate("MainWindow", "Uniform &rectangle", None))
        self.act_grid_manager.setText(_translate("MainWindow", "Grid Manager", None))
        self.act_unite_grids.setText(_translate("MainWindow", "&Unite grids", None))
        self.act_unf_circ.setText(_translate("MainWindow", "Uniform &cirlce", None))
        self.act_movrot.setText(_translate("MainWindow", "&Move/Rotate", None))

import ComGridRes_rc
