JAVAC = javac
JAVA = java


all:
	$(JAVAC) a.java /home/ek/HybMesh/build/bindings/java/Hybmesh.java
	$(JAVA) -Djava.library.path=/home/ek/HybMesh/build/bin -cp ".:/home/ek/HybMesh/build/bindings/java/" a
