# Windows options
#OCTAVE = /c/Octave/Octave-4.2.0/bin/octave-cli.exe 
#MKMEX = /c/Octave/Octave-4.2.0/bin/mkoctfile.exe
#MEXINCLUDE = -I/c/Octave/Octave-4.2.0/include/octave-4.2.0/octave/
#MEXLIBINCLUDE = -L/c/Octave/Octave-4.2.0/lib/
#MEXLIBINCLUDE = -L/c/Octave/Octave-4.2.0/lib/ -L/c/Octave/Octave-4.2.0/lib/octave/4.2.0

# Linux options
OCTAVE = octave-cli 

all:
	$(OCTAVE) a.m
